name: Notify Parent Repo

on:
  push:
    branches: [master]

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: notify
    steps:
      - name: Trigger parent repo update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PARENT_REPO_DISPATCH_TOKEN }}
          repository: d-sektionen/d-sektionen.se
          event-type: submodule-updated
